quarkus.http.port=8081

# Configuracao para assinar o token
smallrye.jwt.sign.key.location=privateKey.pem

# Configuracao para validar o token
mp.jwt.verify.issuer=manager
mp.jwt.verify.publickey.location=publicKey.pem

# Configuracoes do HTTP(S)
quarkus.http.ssl-port=8444
quarkus.http.ssl.certificate.key-store-file=keystore.jks
quarkus.http.ssl.certificate.key-store-password=password
# Configuracao apenas para desenvolvimento
%dev.quarkus.tls.trust-all=true

# Desabilitando o Servidor OpenID padrão
quarkus.keycloak.devservices.enabled=false

# MySQL Configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=
quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.datasource.devservices.port=3306
quarkus.datasource.jdbc.url=jdbc:mysql://127.0.0.1:3306/game_rental
quarkus.datasource.db-version=5.5.5

# Minhas configurações personalizadas
pw2.message=${PW2_MESSAGE:hello}

# Jaeger Configuration
quarkus.otel.service.name=manager
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n

#Graylog
quarkus.log.handler.gelf.enabled=true
quarkus.log.handler.gelf.host=localhost
quarkus.log.handler.gelf.port=12201
